// for getting resource
export const GET_RESOURCE_REQUEST = "GET_RESOURCE_REQUEST";
export const GET_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS";
export const GET_RESOURCE_FAILURE = "GET_RESOURCE_FAILURE";

// for posting resource
export const POST_RESOURCE_REQUEST = "GET_RESOURCE_REQUEST";
export const POST_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS";
export const POST_RESOURCE_FAILURE = "GET_RESOURCE_FAILURE";